---
- name: Example playbook to run pwd command
  hosts: all
  tasks:
    - name: Run pwd command
      shell: pwd
      register: pwd_output
      check_mode: no

    - name: Display the current working directory
      debug:
        msg: "The current working directory is {{ pwd_output.stdout }}"
      check_mode: no
