---
- name: Example playbook to run pwd command
  hosts: all
  tasks:
    - name: Run pwd command
      command: pwd
      register: pwd_output

    - name: Display the current working directory
      debug:
        msg: "The current working directory is {{ pwd_output.stdout }}"
