---
- name: Display Current Working Directory
  hosts: all
  become: true
  tasks:
    - name: Get current working directory
      command: pwd
      register: pwd

    - name: Print the working directory
      debug:
        msg: "The current working directory is: {{ pwd.stdout }}"
